// Generated by gencpp from file gimbal_control_serial/GimbalCmd.msg
// DO NOT EDIT!


#ifndef GIMBAL_CONTROL_SERIAL_MESSAGE_GIMBALCMD_H
#define GIMBAL_CONTROL_SERIAL_MESSAGE_GIMBALCMD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gimbal_control_serial
{
template <class ContainerAllocator>
struct GimbalCmd_
{
  typedef GimbalCmd_<ContainerAllocator> Type;

  GimbalCmd_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , mode(0)  {
    }
  GimbalCmd_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)
    , mode(0)  {
  (void)_alloc;
    }



   typedef float _roll_type;
  _roll_type roll;

   typedef float _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef uint8_t _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> const> ConstPtr;

}; // struct GimbalCmd_

typedef ::gimbal_control_serial::GimbalCmd_<std::allocator<void> > GimbalCmd;

typedef boost::shared_ptr< ::gimbal_control_serial::GimbalCmd > GimbalCmdPtr;
typedef boost::shared_ptr< ::gimbal_control_serial::GimbalCmd const> GimbalCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gimbal_control_serial::GimbalCmd_<ContainerAllocator1> & lhs, const ::gimbal_control_serial::GimbalCmd_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw &&
    lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gimbal_control_serial::GimbalCmd_<ContainerAllocator1> & lhs, const ::gimbal_control_serial::GimbalCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gimbal_control_serial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95e52dfca23ef72d66122799a9e1eabc";
  }

  static const char* value(const ::gimbal_control_serial::GimbalCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95e52dfca23ef72dULL;
  static const uint64_t static_value2 = 0x66122799a9e1eabcULL;
};

template<class ContainerAllocator>
struct DataType< ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gimbal_control_serial/GimbalCmd";
  }

  static const char* value(const ::gimbal_control_serial::GimbalCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 roll\n"
"float32 pitch\n"
"float32 yaw\n"
"uint8 mode\n"
;
  }

  static const char* value(const ::gimbal_control_serial::GimbalCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GimbalCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gimbal_control_serial::GimbalCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gimbal_control_serial::GimbalCmd_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<float>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<float>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GIMBAL_CONTROL_SERIAL_MESSAGE_GIMBALCMD_H
